#!/usr/bin/env ruby
require "pathname"
require Pathname.new(__FILE__).realpath.dirname + "setup_resque"

if ARGV.any? { |a| a =~ /config/ }
  puts "graph_title Resque Workers Count"
  puts "graph_category Resque"
  puts "graph_info This graph shows number of resque workers"
  puts "graph_args --lower-limit 0"
  puts 'graph_vlabel workers'

  puts 'workers_count.label No. of workers'
  puts 'workers_count.type COUNTER'

else
  puts "workers_count.value #{Resque.info[:workers]}"

end
