#!/usr/bin/env ruby
require "pathname"
require Pathname.new(__FILE__).realpath.dirname + "setup_resque"

if ARGV.any? { |a| a =~ /config/ }
  puts "graph_title Resque Failure rate"
  puts "graph_category Resque"
  puts "graph_info This graph shows resque jobs that failed"
  puts "graph_args --lower-limit 0"
  puts 'graph_vlabel fails/s'

  puts 'failed.label Failed per/s'
  puts 'failed.type COUNTER'

else
  puts "failed.value #{Resque.info[:failed]}"

end
