#!/usr/bin/env ruby
require "pathname"
require Pathname.new(__FILE__).realpath.dirname + "setup_resque"

if ARGV.any? { |a| a =~ /config/ }
  puts <<-EOF
graph_title Resque Fails
graph_vlabel jobs per ${graph_period}
graph_category Resque
graph_info This graph shows the failed job count in resque over time
failed.label failed jobs
failed.type COUNTER
failed.cdef failed,1000,*
EOF

else
  puts "failed.value #{Resque.info[:failed]}"

end
